# uncompyle6 version 3.9.0
# Python bytecode version base 2.7 (62211)
# Decompiled from: Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)]
# Embedded file name: .\betterReticleSize-src\scripts\client\gui\mods\betterReticleSize\__init__.py
# Compiled at: 2023-12-31 00:48:56
from gui.Scaleform.daapi.view.battle.shared.crosshair import gm_factory
from gui.Scaleform.genConsts.GUN_MARKER_VIEW_CONSTANTS import GUN_MARKER_VIEW_CONSTANTS as _CONSTANTS
DEFAULT_GUN_MARKER_LINKAGES = gm_factory._GUN_MARKER_LINKAGES
CUSTOM_ARCADE_GUN_MARKER_NAME = _CONSTANTS.ARCADE_GUN_MARKER_NAME + '-SERVER'
CUSTOM_SNIPER_GUN_MARKER_NAME = _CONSTANTS.SNIPER_GUN_MARKER_NAME + '-SERVER'
CUSTOM_DUAL_GUN_ARCADE_MARKER_NAME = _CONSTANTS.DUAL_GUN_ARCADE_MARKER_NAME + '-SERVER'
CUSTOM_DUAL_GUN_SNIPER_MARKER_NAME = _CONSTANTS.DUAL_GUN_SNIPER_MARKER_NAME + '-SERVER'
CUSTOM_SPG_MARKER_NAME = _CONSTANTS.SPG_GUN_MARKER_NAME + '-SERVER'
CUSTOM_GUN_MARKER_LINKAGES = {CUSTOM_ARCADE_GUN_MARKER_NAME: _CONSTANTS.GUN_MARKER_LINKAGE, CUSTOM_SNIPER_GUN_MARKER_NAME: _CONSTANTS.GUN_MARKER_LINKAGE, 
   CUSTOM_DUAL_GUN_ARCADE_MARKER_NAME: _CONSTANTS.DUAL_GUN_ARCADE_MARKER_LINKAGE, 
   CUSTOM_DUAL_GUN_SNIPER_MARKER_NAME: _CONSTANTS.DUAL_GUN_SNIPER_MARKER_LINKAGE, 
   CUSTOM_SPG_MARKER_NAME: _CONSTANTS.GUN_MARKER_SPG_LINKAGE}
CUSTOM_GUN_MARKER_LINKAGES.update(DEFAULT_GUN_MARKER_LINKAGES)
# okay decompiling C:\dev\wot-mods\betterReticleSize-src\scripts\client\gui\mods\betterReticleSize\__init__.pyc
