from gui.Scaleform.daapi.view.battle.shared.crosshair import gm_factory
from gui.Scaleform.genConsts.GUN_MARKER_VIEW_CONSTANTS import GUN_MARKER_VIEW_CONSTANTS as _CONSTANTS

DEFAULT_GUN_MARKER_LINKAGES = gm_factory._GUN_MARKER_LINKAGES

CUSTOM_ARCADE_GUN_MARKER_NAME = _CONSTANTS.ARCADE_GUN_MARKER_NAME + '-SERVER'
CUSTOM_SNIPER_GUN_MARKER_NAME = _CONSTANTS.SNIPER_GUN_MARKER_NAME + '-SERVER'
CUSTOM_DUAL_GUN_ARCADE_MARKER_NAME = _CONSTANTS.DUAL_GUN_ARCADE_MARKER_NAME + '-SERVER'
CUSTOM_DUAL_GUN_SNIPER_MARKER_NAME = _CONSTANTS.DUAL_GUN_SNIPER_MARKER_NAME + '-SERVER'
CUSTOM_SPG_MARKER_NAME = _CONSTANTS.SPG_GUN_MARKER_NAME + '-SERVER'

CUSTOM_GUN_MARKER_LINKAGES = {
   CUSTOM_ARCADE_GUN_MARKER_NAME: _CONSTANTS.GUN_MARKER_LINKAGE,
   CUSTOM_SNIPER_GUN_MARKER_NAME: _CONSTANTS.GUN_MARKER_LINKAGE, 
   CUSTOM_DUAL_GUN_ARCADE_MARKER_NAME: _CONSTANTS.DUAL_GUN_ARCADE_MARKER_LINKAGE, 
   CUSTOM_DUAL_GUN_SNIPER_MARKER_NAME: _CONSTANTS.DUAL_GUN_SNIPER_MARKER_LINKAGE, 
   CUSTOM_SPG_MARKER_NAME: _CONSTANTS.GUN_MARKER_SPG_LINKAGE
}

CUSTOM_GUN_MARKER_LINKAGES.update(DEFAULT_GUN_MARKER_LINKAGES)
