from gui.Scaleform.locale.SETTINGS import SETTINGS
from helpers import i18n

CUSTOM_AIMING_CIRCLE_SHAPE_OPTIONS = [
    i18n.makeString(SETTINGS.AIM_MIXING_TYPE0),
    i18n.makeString(SETTINGS.AIM_MIXING_TYPE1),
    i18n.makeString(SETTINGS.AIM_MIXING_TYPE2),
    i18n.makeString(SETTINGS.AIM_MIXING_TYPE3)
]
CUSTOM_CROSSHAIR_SHAPE_OPTIONS = [
    i18n.makeString(SETTINGS.AIM_GUNTAG_TYPE0),
    i18n.makeString(SETTINGS.AIM_GUNTAG_TYPE1),
    i18n.makeString(SETTINGS.AIM_GUNTAG_TYPE2),
    i18n.makeString(SETTINGS.AIM_GUNTAG_TYPE3),
    i18n.makeString(SETTINGS.AIM_GUNTAG_TYPE4),
    i18n.makeString(SETTINGS.AIM_GUNTAG_TYPE5),
    i18n.makeString(SETTINGS.AIM_GUNTAG_TYPE6),
    i18n.makeString(SETTINGS.AIM_GUNTAG_TYPE7),
    i18n.makeString(SETTINGS.AIM_GUNTAG_TYPE8),
    i18n.makeString(SETTINGS.AIM_GUNTAG_TYPE9),
    i18n.makeString(SETTINGS.AIM_GUNTAG_TYPE10),
    i18n.makeString(SETTINGS.AIM_GUNTAG_TYPE11),
    i18n.makeString(SETTINGS.AIM_GUNTAG_TYPE12),
    i18n.makeString(SETTINGS.AIM_GUNTAG_TYPE13),
    i18n.makeString(SETTINGS.AIM_GUNTAG_TYPE14)
]
